[[plugins]]
repo = 'mattn/vim-sqlfmt'
hook_add = '''
  let g:sqlfmt_program = "sqlformat --comma_first true -r -k upper -o %s -"
  autocmd FileType sql nmap <Leader>F <Plug>(sqlfmt)
'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
  let g:clang_format#style_options = {
    \ "AlignConsecutiveAssignments" : "true",
    \ "AlignConsecutiveDeclarations" : "true",
    \ }
  autocmd FileType proto ClangFormatAutoEnable
'''

[[plugins]]
repo = 'nbouscal/vim-stylish-haskell'
