[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  " python
  if (executable('pylsp'))
      augroup LspPython
          autocmd!
          autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'pylsp',
        \ 'cmd': {server_info->['pylsp']},
        \ 'allowlist': ['python']
        \ })
      augroup END
  endif

  function! s:on_lsp_buffer_enabled() abort
      setlocal omnifunc=lsp#complete
      setlocal signcolumn=yes
      if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
      nmap <buffer> <C-g><C-d> <plug>(lsp-definition)
      nmap <buffer> <C-g><C-s> <plug>(lsp-document-symbol-search)
      nmap <buffer> <C-g><C-w> <plug>(lsp-workspace-symbol-search)
      nmap <buffer> <C-g><C-r> <plug>(lsp-references)
      nmap <buffer> <C-g><C-i> <plug>(lsp-implementation)
      nmap <buffer> <C-g><C-t> <plug>(lsp-type-definition)
      nmap <buffer> <C-g>r <plug>(lsp-rename)
      nmap <buffer> [g <plug>(lsp-previous-diagnostic)
      nmap <buffer> ]g <plug>(lsp-next-diagnostic)
      nmap <buffer> <C-g>d :LspDocumentDiagnostics<CR>
      nmap <buffer> K <plug>(lsp-hover)

      let g:lsp_format_sync_timeout = 1000
      autocmd! BufWritePre *.rs,*.go,*.py call execute('LspDocumentFormatSync')
      autocmd! BufWritePre *.rb,*.rake call execute('LspDocumentFormatSync --server=solargraph')
  endfunction

  augroup lsp_install
      au!
      " call s:on_lsp_buffer_enabled only for languages that has the server registered.
      autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
  augroup END
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_diagnostics_echo_cursor = 1

  " Enable flake8 and mypy
  let g:lsp_settings = {
  \  'pylsp-all': {
  \    'workspace_config': {
  \      'pylsp': {
  \        'configurationSources': ['flake8'],
  \        'plugins': {
  \          'flake8': {
  \            'enabled': 1
  \          },
  \          'mccabe': {
  \            'enabled': 0
  \          },
  \          'pycodestyle': {
  \            'enabled': 0
  \          },
  \          'pyflakes': {
  \            'enabled': 0
  \          },
  \          'pylsp_mypy': {
  \            'enabled': 1
  \          }
  \        }
  \      }
  \    }
  \  }
  \}
'''

[[plugins]]
repo = 'bonprosoft/pysen.vim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
  let g:vista_default_executive = 'vim_lsp'
  nmap <buffer> <C-s><C-v> :Vista!!<CR>
'''
