[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_add = '''
  if executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif

  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nmap <silent> <Leader>ru :QuickRun<CR>
  let g:quickrun_config = {}
  "let g:quickrun_config._ = {
  "\   'runner' : 'vimproc',
  "\   'runner/vimproc/updatetime' : 40,
  "\}
  let g:quickrun_config.python = {
  \ 'command': expand('~/.pyenv/shims/python'),
  \}
  let g:quickrun_config.swift = {
  \ 'command': 'xcrun',
  \ 'cmdopt': 'swift',
  \ 'exec': '%c %o %s',
  \}
  let g:quickrun_config.haskell = {
  \ 'command': 'stack',
  \ 'cmdopt': 'runghc',
  \}
'''

[[plugins]]
repo = 'thosakwe/vim-flutter'

[[plugins]]
repo = 'vim-scripts/dbext.vim'
hook_add = '''
  let g:dbext_default_profile_mysql_local = 'type=MYSQL:host=127.0.0.1:user=root:passwd=root:dbname=test_database'
'''

