[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsJumpForwardTrigger="<tab>"
  let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
  let g:UltiSnipsEditSplit="vertical"
  nnoremap <silent> <C-s><C-n> :UltiSnipsEdit<CR>
'''

[[plugins]]
repo = 'honza/vim-snippets'
depends = ['ultisnips']
